[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
greweco_rwa = "ELHGjVXcokM5Y4nKv6Qff4JKM5CisddnUocs459AUUca"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
